### ISSUE TITLE
Breaks creative search if REI v9.1.610 is installed

### ISSUE THREAD

**Issue by SplendidAlakey** [embeddedt/ModernFix#116]
**MC** 1.19.2
**ModernFix** 3.6.0
**[REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/4558137)** 9.1.610

The issue doesn't happen with REI v9.1.595, but reporting here first, since ModernFix applies some changes to REI. Let me know if this needs to be reported to REI, instead.

To reproduce install both mods and type literally anything in the creative search bar:
![2023-05-30_08 45 15](https://github.com/embeddedt/ModernFix/assets/86702831/d2696743-93b5-43bf-b122-f6be57481d97)

Logs: https://gist.github.com/SplendidAlakey/dac2e42e94b388f00ce64e759020c216

**Comment by embeddedt** [comment]
Please test with the dev build, should already be fixed there.

**Comment by SplendidAlakey** [comment]
Nope, still present in this build https://github.com/embeddedt/ModernFix/actions/runs/5116250818

Should I send the new logs? They are identical, apart from the ModernFix version.

**Comment by embeddedt** [comment]
Oh I didn't notice the issue came from a REI version change.

**Comment by embeddedt** [comment]
Ok, *now* the dev build should fix it. :laughing:

**Comment by SplendidAlakey** [comment]
Yep, fixed.

**Comment by embeddedt** [comment]
Latest release includes the fix.
