### ISSUE TITLE
[1.16.5] ModernFix and Decocraft crashing together

### ISSUE THREAD

**Issue by sirben99** [embeddedt/ModernFix#187]
Hey!

Im having a crash with the mod Decocraft (https://www.curseforge.com/minecraft/mc-mods/decocraft) where Decocraft loads incorrectly and crashes.

Couple of things to note:

1. Im not sure whos fault this is per say, but i decided to report here first to see if its on ModernFixes end to fix. If this should be reported to Decocraft, please let me know and ill re-direct this!
2. I am aware that Decocraft is in alpha, and this should be expected. I still decided to report this issue in case it affects something else or a more major issue is found by it

Minecraft: 1.16.5
Modloader: Forge
ModernFix: 5.4.0
Decocraft: 3.0.0.12 Alpha

Crash report: https://pastebin.com/Q3fqBd4A
Log (I tried to paste the log, but Pastebin would crash since its so big):
[latest.log](https://github.com/embeddedt/ModernFix/files/12176063/latest.log)

Thank you for your time!

**Comment by embeddedt** [comment]
Thanks for the report, should be fixed in 5.4.1.

**Comment by sirben99** [comment]
I can confirm that the crash has been fixed in the new release. Thank you for looking into this!

**Comment by sirben99** [comment]
After more testing, it seems that Decocraft is still crashing with ModernFix, but only in my modpack. They work as standalone together with the new update, but seems like they dont want to work together in my modpack. Removing ModernFix fixes the crash. Is this a ModernFix issue per say or is a third mod intervening?

Crash: https://pastebin.com/GCCLMj9L
Log: 
[latest.log](https://github.com/embeddedt/ModernFix/files/12185582/latest.log)

**Comment by embeddedt** [comment]
Does this version work in the full pack?

[test.zip](https://github.com/embeddedt/ModernFix/files/12185809/test.zip)

**Comment by sirben99** [comment]
That version works with the full pack! Not crashing anymore

**Comment by embeddedt** [comment]
Ok, released as 5.4.2.
