### ISSUE TITLE
1.16 Maybe there is a mistake with async_locator

### ISSUE THREAD

**Issue by 2929762171** [embeddedt/ModernFix#241]
mixin.perf.async_locator
Causes all structural maps to be invalid.
![image](https://github.com/embeddedt/ModernFix/assets/98941945/8ff58a22-a70a-4f49-afae-c46a22bb6b9b)

(Actually, I encountered this problem several months ago. But I didn't realize it was a modernfix problem.)

**Comment by embeddedt** [comment]
Does it occur in a standalone instance with only ModernFix (plus maybe a mod that adds a custom structure, if it doesn't happen with vanilla structures)?

**Comment by 2929762171** [comment]
> 它是否发生在仅具有 ModernFix 的独立实例中（如果它不会发生在普通结构中，则可能加上添加自定义结构的 mod）？

I'll test it when I have time, I'm a little busy this week...

**Comment by wasdspace** [comment]
Same. I tried to reproduce it with a clean instance, but finding a treasure map in vanilla killed me lol.
Async Locator seems to have fixed this bug in the June update, so maybe we should synchronize with upstream?
https://legacy.curseforge.com/minecraft/mc-mods/async-locator/files/4593926

**Comment by embeddedt** [comment]
I've made some changes to improve reliability of this feature in the next release (testable now with the beta in the README). In my tests, vanilla structure maps seem to work without issues.

**Comment by 2929762171** [comment]
> 我做了一些更改，以提高下一个版本中此功能的可靠性（现在可以使用 README 中的测试版进行测试）。在我的测试中，普通结构图似乎可以正常工作。

Fine.

**Comment by embeddedt** [comment]
This should hopefully be fixed as of 5.7.4.

**Comment by 2929762171** [comment]
It did work, but it was a little slow to load.
And it still doesn't work properly in command " /loot ".
Like:
/loot give @p loot minecraft:chests/shipwreck_map

**Comment by embeddedt** [comment]
Good catch; it seems to be an issue with the original Async Locator mod as well (which my patch is a backport of), so I've reported it there: https://github.com/thebrightspark/AsyncLocator/issues/10
